version: '3'
services:

    # The Application
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - "../${PROJECT_FOLDER:-laravel}:/var/www"
            - ./app.ini:/usr/local/etc/php/conf.d/app.ini
        links:
            - dbserver

        # The Web Server
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - "../${PROJECT_FOLDER:-laravel}:/var/www"
            - ./app.ini:/usr/local/etc/php/conf.d/app.ini
        ports:
            - ${WEB_PORT:-80}:80
    dbserver:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports: 
            - ${MYSQL_PORT:-3306}:3306
        hostname: dbserver
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
        volumes:
            - ../db_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        depends_on: 
            - dbserver
        ports:
            - ${PMA_PORT:-81}:80
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: dbserver
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
